"""Added message_type to the Message table

Revision ID: 2d22972fd966
Revises: 46eb0d369ead
Create Date: 2025-02-02 17:01:36.165313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d22972fd966'
down_revision: Union[str, None] = '46eb0d369ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
