"""add_message_grouping_fields

Revision ID: 3a15a43c3b1a
Revises: 2d22972fd966
Create Date: 2025-02-23 22:56:48.882038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a15a43c3b1a'
down_revision: Union[str, None] = '2d22972fd966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_agents')
    op.add_column('messages', sa.Column('iteration_index', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('step_index', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('step_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'step_title')
    op.drop_column('messages', 'step_index')
    op.drop_column('messages', 'iteration_index')
    op.create_table('chat_agents',
    sa.Column('chat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='chat_agents_agent_id_fkey'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='chat_agents_chat_id_fkey'),
    sa.PrimaryKeyConstraint('chat_id', 'agent_id', name='chat_agents_pkey')
    )
    # ### end Alembic commands ###
