"""add_model_column_to_messages

Revision ID: 3dda4dbdf265
Revises: 9e27e587d5a2
Create Date: 2025-01-02 13:54:30.080820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dda4dbdf265'
down_revision: Union[str, None] = '9e27e587d5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_users_azure_id', table_name='users')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'name')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'azure_id')
    op.drop_column('users', 'token_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('azure_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_azure_id', 'users', ['azure_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('messages', 'model')
    # ### end Alembic commands ###
