"""Added repository to Agent

Revision ID: 46eb0d369ead
Revises: e2a3143ed299
Create Date: 2025-02-02 15:45:45.422403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46eb0d369ead'
down_revision: Union[str, None] = 'e2a3143ed299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('repository', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'repository')
    # ### end Alembic commands ###
