"""add_messages_relationship_back_to_chat

Revision ID: 636c6a2dda13
Revises: a8f4b0354309
Create Date: 2024-12-30 16:09:36.694647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636c6a2dda13'
down_revision: Union[str, None] = 'a8f4b0354309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
