"""adding_agents_relations_to_messages_and_chat

Revision ID: 79480f9d8281
Revises: 73ebec191d27
Create Date: 2025-01-22 15:42:25.829966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79480f9d8281'
down_revision: Union[str, None] = '73ebec191d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'agent_id')
    # ### end Alembic commands ###
