"""add_azure_related_features_to_user

Revision ID: 9b5205075a38
Revises: 636c6a2dda13
Create Date: 2024-12-30 19:44:36.895093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5205075a38'
down_revision: Union[str, None] = '636c6a2dda13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('azure_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_azure_id'), 'users', ['azure_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_azure_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'name')
    op.drop_column('users', 'azure_id')
    # ### end Alembic commands ###
