"""Added pipeline_id to the Message table

Revision ID: add_pipeline_id_to_messages
Revises: 2d22972fd966
Create Date: 2025-05-15 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_pipeline_id_to_messages"
down_revision: Union[str, None] = "3a15a43c3b1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("pipeline_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "pipeline_id")
    # ### end Alembic commands ###
