"""Added repository name Messages

Revision ID: e2a3143ed299
Revises: fc45a337dce5
Create Date: 2025-02-02 14:59:24.215440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a3143ed299'
down_revision: Union[str, None] = 'fc45a337dce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('repository', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'repository')
    # ### end Alembic commands ###
