"""adding_agents

Revision ID: fc27d26eb999
Revises: 3dda4dbdf265
Create Date: 2025-01-02 15:35:19.989595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc27d26eb999'
down_revision: Union[str, None] = '3dda4dbdf265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('chats', sa.Column('agent_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chats', 'agents', ['agent_id'], ['id'])
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_users_azure_id', table_name='users')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'azure_id')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('azure_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_azure_id', 'users', ['azure_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'agent_id')
    op.drop_table('agents')
    # ### end Alembic commands ###
