"""Added Agent ID to Messages

Revision ID: fc45a337dce5
Revises: 878979b6a41d
Create Date: 2025-01-29 19:09:34.804540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc45a337dce5'
down_revision: Union[str, None] = '878979b6a41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'agent_id')
    # ### end Alembic commands ###
